#!/usr/bin/env python3
"""PreToolUse:Bash — deny destructive commands and redirect wrong-tool calls.

Two jobs, both deterministic:
  1. Refuse commands that are hard or impossible to undo.
  2. Redirect a command to this repo's actual tooling (wrong package manager,
     wrong test runner) before it runs and produces a confusing failure.

The second job is the token saver: a denial with a corrective reason costs a
few dozen tokens, whereas letting the wrong command run costs the failure
output plus a recovery turn.
"""
import os
import re
import sys

from _common import deny, load_config, load_payload

# Deny outright. Kept deliberately tight — a false positive here blocks real work.
HARD_DENY = [
    (r":\(\)\s*\{.*\};\s*:", "Fork bomb pattern."),
    (r"\bmkfs\b|\bdd\s+if=.*\bof=/dev/", "Writes directly to a device."),
    (r"\bchmod\s+(-[a-zA-Z]+\s+)*777\b", "chmod 777 — set a specific mode instead."),
    (r"\bcurl\b[^|;]*\|\s*(sudo\s+)?(ba)?sh",
     "Piping a download straight into a shell. Download, read, then run."),
    (r"\bgit\s+reset\s+--hard\b",
     "git reset --hard discards uncommitted work. Use git stash, or ask me."),
    (r"\bgit\s+clean\s+(-[a-zA-Z]*\s*)*-[a-zA-Z]*f",
     "git clean -f deletes untracked files permanently."),
    (r"\bgit\s+push\b[^|;]*--force(?!-with-lease)",
     "Bare --force push. Use --force-with-lease, or ask me."),
    (r"\bhistory\s+-c\b|\brm\b[^|;]*\.git/", "Touches git internals or shell history."),
]

SECRET_READ = re.compile(
    r"\b(cat|less|more|head|tail|bat|strings|xxd)\b[^|;&]*"
    r"(\.env(\.[a-zA-Z0-9_-]+)?|id_rsa|id_ed25519|\.pem\b|credentials\b|\.netrc)"
)
# .env.example and friends are checked into the repo on purpose.
SECRET_EXEMPT = re.compile(r"\.(example|sample|template|dist)\b|\.env\.example")

# Recursive delete is denied by default, except for directories that are
# regenerated by a build or an install. Extend via allowedDeletes in config.
DEFAULT_ALLOWED_DELETES = [
    "node_modules", "dist", "build", "out", ".next", ".turbo", "coverage",
    "__pycache__", ".pytest_cache", ".mypy_cache", "target", ".venv",
]
RECURSIVE_RM = re.compile(
    r"\brm\s+(?P<flags>(?:-[a-zA-Z]+\s+)*)(?P<targets>[^;&|]*)")


def main():
    payload = load_payload()
    if payload.get("tool_name") != "Bash":
        return 0

    command = (payload.get("tool_input") or {}).get("command", "")
    if not command.strip():
        return 0

    config = load_config()

    for match in RECURSIVE_RM.finditer(command):
        if "r" not in match.group("flags").lower():
            continue
        allowed = config.get("allowedDeletes", DEFAULT_ALLOWED_DELETES)
        targets = [t for t in match.group("targets").split() if not t.startswith("-")]
        stray = [t for t in targets
                 if os.path.basename(t.strip("'\"").rstrip("/")) not in allowed]
        if stray or not targets:
            deny(
                "Blocked by guard-bash: recursive delete of %s. Only regenerable "
                "directories (%s and similar) may be removed this way — delete "
                "anything else by name, or ask me to run it."
                % (", ".join(stray) or "an unnamed target", ", ".join(allowed[:4]))
            )

    for pattern, reason in HARD_DENY:
        if re.search(pattern, command):
            deny("Blocked by guard-bash: %s" % reason)

    if SECRET_READ.search(command) and not SECRET_EXEMPT.search(command):
        deny(
            "Blocked by guard-bash: that reads a secrets file. "
            "Ask me for the value you need, or read the .example file instead."
        )

    # Project-specific redirects, e.g. npm -> pnpm, pytest -> uv run pytest.
    for rule in config.get("bannedCommands", []):
        pattern = rule.get("pattern")
        if pattern and re.search(pattern, command):
            deny("Blocked by guard-bash: %s" % rule.get("reason", "not allowed here"))

    # Commit policy. "ask" surfaces a prompt; "deny" refuses outright.
    policy = config.get("commitPolicy", "allow")
    if policy != "allow" and re.search(r"\bgit\s+commit\b", command):
        if policy == "deny":
            deny("This repo does not commit from agent sessions. Stage the work "
                 "and leave the commit to a human.")
        print(
            '{"hookSpecificOutput":{"hookEventName":"PreToolUse",'
            '"permissionDecision":"ask",'
            '"permissionDecisionReason":"Commit requires explicit approval in this repo."}}'
        )
        return 0

    # Protected branches: refuse pushes from a branch we should not be on.
    protected = config.get("protectedBranches", [])
    if protected and re.search(r"\bgit\s+push\b", command):
        code, branch = _current_branch(payload)
        if code == 0 and branch in protected:
            deny("Refusing to push directly to '%s'. Open a branch and a PR." % branch)

    return 0


def _current_branch(payload):
    from _common import repo_root, run
    return run("git rev-parse --abbrev-ref HEAD", repo_root(payload), timeout=10)


if __name__ == "__main__":
    sys.exit(main())
